application: pascra619
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: pascra.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"                                                                      
- name: jinja2                                                                  
  version: latest     
- name: lxml                                                                  
  version: latest     
  